#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication gmsh subChannelHex -3 -format msh2 -o subChannelHexMesh
runApplication gmshToFoam subChannelHexMesh
runApplication transformPoints "scale=(0.01 0.01 0.01)"
changeDictionary
runApplication splitMeshRegions -cellZonesOnly -overwrite
